config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :programs do
  	collection do
  		get 'search'
  	end
  end
  
  root 'pages#home'
  get 'pages/about'
  get 'pages/service'
  get 'pages/faq'
  get 'pages/contact'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/program.rb
class Program < ApplicationRecord
	mount_uploader :image, ImageUploader

	has_many_attached :uploads
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
 

  mount_uploader :image, ImageUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 
  # User Avatar Validation
  validates_integrity_of  :image
  validates_processing_of :image
 
  private
    def image_size_validation
      errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	 protect_from_forgery with: :exception

	 before_action :configure_permitted_parameters, if: :devise_controller?

	  protected

		  def configure_permitted_parameters
		  devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
		  devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name])
		 
		  
		  
		  devise_parameter_sanitizer.permit(:account_update, keys: [:first_name])
		  devise_parameter_sanitizer.permit(:account_update, keys: [:last_name])
		  devise_parameter_sanitizer.permit(:account_update, keys: [:image])
		  devise_parameter_sanitizer.permit(:account_update, keys: [:image_cache])
		  devise_parameter_sanitizer.permit(:account_update, keys: [:remove_image])
		  end



end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def service
  end

  def faq
  end

  def contact
  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show, :edit, :update, :destroy] 
  before_action :authenticate_user!, except: [:search, :index, :show]
  
   def search
  if params[:search].present?
      @programs = Program.search(params[:search])
    else
      @programs = Program.all
    end
  end
  
  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
  end

  # GET /programs/new
  def new
    @program = Program.new
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(program_params)

    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render :show, status: :created, location: @program }
      else
        format.html { render :new }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { render :show, status: :ok, location: @program }
      else
        format.html { render :edit }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to programs_url, notice: 'Program was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def program_params
      params.require(:program).permit(:name, :image, :lecturers, :description, :level, :prerequisite, :literature, :syllabus, :hours, :skills, :workload, :faq, :capacity, :studyboard, :faculty, :remove_uploads,uploads: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Edulib | Study Courses Online</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
 <!-- Font Awesome -->
  <link rel="stylesheet" href="/plugins/fontawesome-free/css/all.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="/https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

  <!-- iCheck -->
  <link rel="stylesheet" href="/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
  <!-- JQVMap -->
  <link rel="stylesheet" href="/plugins/jqvmap/jqvmap.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/dist/css/adminlte.min.css">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="/plugins/daterangepicker/daterangepicker.css">
  <!-- summernote -->
  <link rel="stylesheet" href="/plugins/summernote/summernote-bs4.css">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  </head>

  <body class= "sidebar-mini layout-fixed" style="height: auto">
 

    
    <% if (request.original_url != root_url) && (!current_page?(new_user_session_path) && !current_page?(new_user_registration_path)) then %> 
    
    <%= render 'shared/navbar'%>
    <%= render 'shared/aside'%>   
    <% end %>



      <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
          <div class="alert alert-<%= name.to_s == "notice" ? "success" : "danger" %> alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
          </div>
        <% end %>
      <% end %>
    <%= yield %>
 
      <% if (request.original_url != root_url) && (!current_page?(new_user_session_path) && !current_page?(new_user_registration_path)) then %> 
    
    <%= render 'shared/footer'%> 

     <% end %>
    


     <% if (request.original_url == root_url)  || (current_page?(new_user_session_path) || current_page?(new_user_registration_path)) then %>
         <%= render 'shared/footer1'%> 
      <% end %> 

      <script src="js/main.js"></script>

      <script>
        $.widget.bridge('uibutton', $.ui.button)
      </script>

      <!-- ChartJS -->
      <script src="/plugins/chart.js/Chart.min.js"></script>
      <!-- Sparkline -->
      <script src="/plugins/sparklines/sparkline.js"></script>
      <!-- JQVMap -->
      <script src="/plugins/jqvmap/jquery.vmap.min.js"></script>
      <script src="plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
      <!-- jQuery Knob Chart -->
      <script src="/plugins/jquery-knob/jquery.knob.min.js"></script>
      <!-- daterangepicker -->
      <script src="/plugins/moment/moment.min.js"></script>
      <script src="/plugins/daterangepicker/daterangepicker.js"></script>

      <!-- Summernote -->
      <script src="/plugins/summernote/summernote-bs4.min.js"></script>
      <!-- overlayScrollbars -->
      <script src="/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
  </body>


</html>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/faq.html.erb
<h1>Pages#faq</h1>
<p>Find me in app/views/pages/faq.html.erb</p>

app/views/programs/edit.html.erb
<div class="content-wrapper" style="min-height: 1894.8px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Editing Program</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item"><a href="#">Layout</a></li>
              <li class="breadcrumb-item active">Editing Layouts</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <!-- Default box -->
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Title</h3>

                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fas fa-minus"></i></button>
                  <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fas fa-times"></i></button>
                </div>
              </div>
              <div class="card-body">
               <%= render 'form', program: @program %>

				<%= link_to 'Show', @program, class: "btn btn-link" %> |
				<%= link_to 'Back', programs_path, class: "btn btn-link" %>

              </div>
              <!-- /.card-body -->
              <div class="card-footer">
                Footer
              </div>
              <!-- /.card-footer-->
            </div>
            <!-- /.card -->
          </div>
        </div>
      </div>
    </section>
    <!-- /.content -->
  </div>

app/views/programs/index.html.erb
<div class="content-wrapper" style="min-height: 1894.8px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h3>Popular Courses</h3>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item"><a href="#">Layout</a></li>
              <li class="breadcrumb-item active">Courses</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <!-- Default box -->
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Title</h3>

                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fas fa-minus"></i></button>
                  <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fas fa-times"></i></button>
                </div>
              </div>
              <div class="card-body">
                
                  <hr>


                  <div class="center">
               
                        <div class="row">
                                <% @programs.each do |program| %>
                                        <div class="col-md-3">
                                               
                                                <div class="thumbnail">
                                                         
                                                              <div class="card">
                                                               <%= link_to image_tag(program.image.url), program, class: "card_img" %>
                                                                            <div class="card_content">
                                                                                  <h5 class="card_header"><%= link_to program.name, program %></h5>
                                                                                
                                                                                  <p class="card_text">Created By <%= program.lecturers %></p>

                                                                                  <p>
                                                                                    Level:
                                                                                    <strong><%= program.level %></strong>
                                                                                  </p>

                                                                                       
                                                                                        <%= link_to 'Explore', program, class: "btn carb_btn" %>
                                                                                        <% if (user_signed_in?) %>
                                                                                            <%= link_to 'Edit', edit_program_path(program), class: "btn btn-link" %>
                                                                                            <%= link_to 'Destroy', program, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %>
                                                                                            
                                                                                        <% end %>
                                                                                        <br>
                                                                                </div>
                                                                  </div>
                                                              
                                                    </div>


                                        </div>
                                  <% end %>
                                
                        </div>
                  </div>

                  <hr>

                  <%= link_to 'New Program', new_program_path, class: "btn btn-link" %>



              </div>
              <!-- /.card-body -->
             
            </div>
            <!-- /.card -->
          </div>
        </div>
      </div>
    </section>
    <!-- /.content -->
</div>

app/views/programs/new.html.erb
<div class="content-wrapper" style="min-height: 1894.8px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h3>Add Course</h3>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item"><a href="#">Layout</a></li>
              <li class="breadcrumb-item active">Courses</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <!-- Default box -->
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Add Program</h3>

                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fas fa-minus"></i></button>
                  <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fas fa-times"></i></button>
                </div>
              </div>
              <div class="card-body">
            
				<%= render 'form', program: @program %>

				<%= link_to 'Back', programs_path, class: "btn btn-link" %>

              </div>
              <!-- /.card-body -->
             
            </div>
            <!-- /.card -->
          </div>
        </div>
      </div>
    </section>
    <!-- /.content -->
  </div>

app/views/programs/search.html.erb
<div class="content-wrapper" style="min-height: 1894.8px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h2>Search:\></h2>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item"><a href="#">Layout</a></li>
              <li class="breadcrumb-item active">Search</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <!-- Default box -->
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Title</h3>

                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fas fa-minus"></i></button>
                  <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fas fa-times"></i></button>
                </div>
              </div>
              <div class="card-body">
                                   
                    <table class="table table-borderless table-striped table-hover table-condensed">
                      <thead>
                        <tr>
                          <th>Name</th>
                          <th>Image</th>
                          <th>Lecturers</th>
                          <th>Description</th>
                          <th>Level</th>
                          <th>Prerequisite</th>
                          <th>Literature</th>
                          <th>Syllabus</th>
                          <th>Hours</th>
                          <th>Skills</th>
                          <th>Workload</th>
                          <th>Faq</th>
                          <th>Capacity</th>
                          <th>Study board</th>
                          <th>Faculty</th>
                          <% if user_signed_in? %>
                          <th colspan="3"></th>
                          <% end %>
                        </tr>
                      </thead>

                      <tbody>
                        <% @programs.each do |program| %>
                          <tr>
                            <td><%= link_to program.name, program %></td>
                            <td><%= link_to image_tag(program.image.url), program %></td>
                            <td><%= program.lecturers %></td>
                            <td><%= program.description %></td>
                            <td><%= program.level %></td>
                            <td><%= program.prerequisite %></td>
                            <td><%= program.literature %></td>
                            <td><%= program.syllabus %></td>
                            <td><%= program.hours %></td>
                            <td><%= program.skills %></td>
                            <td><%= program.workload %></td>
                            <td><%= program.faq %></td>
                            <td><%= program.capacity %></td>
                            <td><%= program.study_board %></td>
                            <td><%= program.faculty %></td>
                            <td><%= link_to 'Show', program %></td>
                            <% if user_signed_in? %>
                            <td><%= link_to 'Edit', edit_program_path(program) %></td>
                            <td><%= link_to 'Destroy', program, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                            <% end %>
                          </tr>
                        <% end %>
                      </tbody>
                    </table>


              </div>
              <!-- /.card-body -->
            
            </div>
            <!-- /.card -->
          </div>
        </div>
      </div>
    </section>
    <!-- /.content -->
  </div>

app/views/programs/show.html.erb
  <div class="content-wrapper" style="min-height: 1894.8px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h3>Add Course</h3>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item"><a href="#">Layout</a></li>
              <li class="breadcrumb-item active">Courses</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <!-- Default box -->
            <div class="card">
              <div class="card-header">
                <h3 class="card-title"><%= @program.name %></h3>

                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fas fa-minus"></i></button>
                  <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fas fa-times"></i></button>
                </div>
              </div>
              <div class="card-body">
                    



              <div class="row">


              <div class="col-md-3">


          
                  <p>
                          <%= image_tag @program.image_url %>
                  </p>
       
                  <p>
                      <h5><strong><%= @program.name %></strong></h5>
                  </p>
          
                  
                  <p>
                    <strong>Level:</strong>
                    <%= @program.level %>
                  </p>

                  <p>
                    <strong>Lecturers:</strong>
                    <%= @program.lecturers %>
                  </p>
        



              </div>

              <div class="col-md-9">




              <nav>
                  <div class="nav nav-tabs" id="nav-tab" role="tablist">
                    <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Description</a>

                    <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false"> Pre-requisite</a>

                    <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false"><i class="fas fa-file-pdf"></i> Syllabus</a>

                     <a class="nav-item nav-link" id="nav-lecture-tab" data-toggle="tab" href="#nav-lecture" role="tab" aria-controls="nav-lecture" aria-selected="false"><i class="fas fa fa-download"></i> Lectures</a>

                  </div>
                </nav>
                <div class="container-fluid">
                  <div class="tab-content" id="nav-tabContent">
                        <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab"> <div>
                              <p>                        
                                <h5><strong>Description:</strong></h5><br>
                                  <%= @program.description %>
                                </p>
                                <br>


                                <p>
                                  <strong>Capacity:</strong>
                                  <%= @program.capacity %>
                                </p>

                                <p>
                                  <strong>Study Board:</strong>
                                  <%= @program.studyboard %>
                                </p>

                                <p>
                                  <strong>Faculty:</strong>
                                  <%= @program.faculty %>
                                </p>
                        </div>

                  </div>
                  <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
                    <div>
                      <p>
                        <h5><strong>Pre-requisite:</strong></h5><br>
                        <%= @program.prerequisite %>
                      </p>
                      <br>
                      <p>
                        <strong>Literature:</strong>
                        <%= @program.literature %>
                      </p>

                      <p>
                        <strong>Faq:</strong>
                        <%= @program.faq %>
                      </p>

                    </div>


                  </div>

                  <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
                               <p class="text-lg">
                                  <h5><strong>The list of the course schedule is below:</strong></h5><br>
                               </p>
                                

                                <p>
                                  <strong>Syllabus:</strong>
                                  <%= @program.syllabus %>
                                </p>
                                <br>
                                <p>
                                  <strong>Hours:</strong>
                                  <%= @program.hours %>
                                </p>

                                <p>
                                  <strong>Skills:</strong>
                                  <%= @program.skills %>
                                </p>

                                <p>
                                  <strong>Workload:</strong>
                                  <%= @program.workload %>
                                </p>


                  </div>
                  <div class="tab-pane fade" id="nav-lecture" role="tabpanel" aria-labelledby="nav-lecture-tab">
                      <div>
                          <p class="text-lg">
                            <h5><strong>Lecture Materials:</strong></h5><br>
                          </p>
                      
                          <% @program.uploads.each do |upload| %>
                            <p>
                              
                              <%= link_to upload.filename, rails_blob_path(upload, disposition: :attachment) %>
                            </p>
                          <% end %>
                      </div>
                  </div>

               </div>






               </div>
               </div>



              </div>
              <!-- /.card-body -->
             
              <div class="card-footer">
              
                <%= link_to 'Edit', edit_program_path(@program), class: "btn btn-link" %> |
                <%= link_to 'Back', programs_path, class: "btn btn-link" %>
              </div>

            </div>
            <!-- /.card -->
          </div>
        </div>
      </div>
    </section>
    <!-- /.content -->
  </div>

app/views/shared/_navbar.html.erb
<nav class="main-header navbar navbar-expand navbar-white navbar-light text-sm">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="../../index3.html" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
    
      
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="fas fa-envelope mr-2"></i>
          
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <br>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
       </li>
     
              <% if (!user_signed_in?) %>
                   <li class="nav-item"><%= link_to "Sign up", new_user_registration_path, class: "nav-link" %></li>
               
                   <li class="nav-item"><%= link_to "Sign in", new_user_session_path, class: "btn btn-primary"%></li>


              <% else %>
              



              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa fa-user"></i>
                  <%= current_user.first_name.capitalize %> <%= current_user.last_name.capitalize[0] %>.<span class="caret"></span>
                </a>

                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              
                  <%= link_to "My Courses", programs_path, class: "dropdown-item" %>
                  
                  <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item"%> 
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Account Settings</a>
                </div>
              </li>
              
              <li class="nav-item"><%= link_to "Sign out", destroy_user_session_path, class: "nav-link", method: :delete %></li>

             <% end %>
    </ul>
  </nav>